t2 encryption/decryption
commerceblock/mercury pull request #138
Opened 2021-02-18 08:18 UTC by tomt1664

t2 is encrypted by client in TransferMsg4 with the SE public key share, and decrypted by the SE. 

SE public key share (`s1pubkey`) saved to UserSession DB during keygen. 

`s1pubkey` retrieved from SE by client in `transfer_receiver` (new route/API).

2021-02-18 10:30 UTC, lawlawlaw requested changes
The integration tests are failing.

2021-02-18 11:22 UTC, tomt1664 commented on client/src/state_entity/transfer.rs
> +
Seem to pass for me:

```
running 11 tests
test batch_transfer_test::tests::test_batch_sigs ... ok
test batch_transfer_test::tests::test_batch_transfer ... ok
test batch_transfer_test::tests::test_swap ... ok
test test::tests::test_deposit ... (took PT12.815056S) ok
test test::tests::test_double_transfer ... (took PT28.618710S) ok
test test::tests::test_failed_auth ... (took PT7.280963S) ok
test test::tests::test_gen_shared_key ... (took PT8.971876S) ok
test test::tests::test_get_statechain ... (took PT12.816219S) ok
test test::tests::test_transfer ... (took PT21.442968S) ok
test test::tests::test_wallet_load_with_shared_key ... (took PT12.338556S) ok
test test::tests::test_withdraw ... (took PT16.854560S) ok
```

But pushed change.

2021-02-18 22:15 UTC, tomt1664 commented
I changed the serialisation of the pubkey to compressed hex string.

2021-02-19 09:27 UTC, lawlawlaw approved these changes

2021-02-19 15:28 UTC, merged