Deposit vdf
commerceblock/mercury pull request #227
Opened 2021-07-22 15:42 UTC by tomt1664

Proof of work via a verifiable delay function is now required to generate a new shared key. 

The VDF challenge (a random 32 byte number) is returned from deposit_init, and the solution (which requires a few seconds of computation) is then returned and verified as part of keygen_first.

2021-07-23 16:23 UTC, lawlawlaw requested changes
- Remove the .DS_Store files
- There was a compile error when compiling the tests:
error[E0593]: closure is expected to take 4 arguments, but it takes 3 arguments
   --> integration-tests/src/test.rs:631:14
    |
631 |             .returning(|_user_id, _auth, _proof_key| Ok(()));
    |              ^^^^^^^^^ ----------------------------- takes 3 arguments
    |              |
    |              expected closure that takes 4 arguments

2021-07-23 16:23 UTC, lawlawlaw commented on server/Settings.toml
> +network = "regtest"
revert to testnet

2021-07-26 00:32 UTC, lawlawlaw approved these changes

2021-07-26 00:35 UTC, lawlawlaw requested changes
.DSStore files should be removed.

2021-07-28 10:28 UTC, tomt1664 commented
VDF replaced with sha3 PoW. Challenge is now a 16 byte hex string, and solution a variable length hex string.

2021-07-28 19:04 UTC, merged