Watchblock
commerceblock/mercury pull request #81
Opened 2020-09-21 07:49 UTC by tomt1664

Settings, logic and verification to handle locktime decrementing backup transactions. 

Watch-only config option (that only reads/writes to BackupTx table). 

Watch option that connects directly to bitcoind.

2020-09-21 10:14 UTC, lawlawlaw commented
I get the following build errors:

   Compiling shared v0.2.0 (/Users/lawrence/Projects/mercury/shared)
error[E0432]: unresolved import `electrumx_client::response::GetTipResponse`
 --> shared/src/mocks/mock_electrum.rs:8:31
  |
8 |     GetTransactionConfStatus, GetTipResponse,
  |                               ^^^^^^^^^^^^^^ no `GetTipResponse` in `response`

error[E0407]: method `get_tip_header` is not a member of trait `Electrumx`
  --> shared/src/mocks/mock_electrum.rs:20:5
   |
20 | /     fn get_tip_header(&mut self) -> std::result::Result<GetTipResponse, Box<dyn std::error::Error>> {
21 | |         todo!()
22 | |      }
   | |______^ not a member of trait `Electrumx`

error[E0308]: `match` arms have incompatible types
   --> shared/src/mainstay.rs:324:27
    |
301 |  /             match res.json::<serde_json::Value>() {
302 |  |                 Ok(j) => {
303 |  |                     let response = Response::from_json(&j)?;
304 |  |                     match response.response.as_str() {
    |  |_____________________-
305 | ||                         Some(r) => match r == "Commitment added" {
306 | ||                             true => return Ok(()),
307 | ||                             false => {
...   ||
321 | ||                         }
322 | ||                     }
    | ||_____________________- this is found to be of type `()`
323 |  |                 }
324 |  |                 Err(e) => Err(e.into()),
    |  |                           ^^^^^^^^^^^^^ expected `()`, found enum `std::result::Result`
325 |  |             }
    |  |_____________- `match` arms have incompatible types
    |
    = note: expected type `()`
               found enum `std::result::Result<_, _>`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0407, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `shared`.

2020-09-22 08:50 UTC, lawlawlaw requested changes
See comments

2020-09-22 08:50 UTC, lawlawlaw commented on client/src/main.rs
> +    let network = "regtest".to_string();
Why change from testnet to regtest?

2020-09-22 08:50 UTC, lawlawlaw commented on server/Settings.toml
> +mainstay_config = {url = "https://mainstay.xyz/api/v1", position = 6, token = "4135fe4d-a687-4f78-8f44-30aa57d88299"}
Should not be public

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/protocol/deposit.rs
> +        println!("{:?}","HERE 1" );
Remove

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/protocol/util.rs
> +                if (prepare_sign_msg.tx.lock_time as u32) >= (500000000 as u32) {
Please create a max lock time constant with value 500000000 rather than use a literal

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/storage/monotree.rs
> +    fn get_current_backup_txs(&self, _locktime: i64) -> crate::Result<Vec<crate::structs::BackupTxID>> {
Unimplemented?

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/watch.rs
> +    let mut sc_entity = PGDatabase::get_new();
Should use a mock database if in a unit test. See, for example, server/src/conductor/protocol.rs lines 34-43: 

cfg_if! {
    if #[cfg(any(test,feature="mockdb"))]{
        use crate::MockDatabase;
        use monotree::database::MemoryDB;
        type SCE = StateChainEntity::<MockDatabase, MemoryDB>;
    } else {
        use crate::PGDatabase;
        type SCE = StateChainEntity::<PGDatabase, PGDatabase>;
    }
}

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/watch.rs
> +}
Tests needed

2020-09-22 08:50 UTC, lawlawlaw commented on server/src/protocol/util.rs
> -                tx_backup_verify(&prepare_sign_msg)?;
Why is this not needed?

2020-09-22 12:59 UTC, tomt1664 commented on client/src/main.rs
> +    let network = "regtest".to_string();
This was just for local testing - I'll revert

2020-09-22 13:01 UTC, tomt1664 commented on server/Settings.toml
> +mainstay_config = {url = "https://mainstay.xyz/api/v1", position = 6, token = "4135fe4d-a687-4f78-8f44-30aa57d88299"}
Whoops. I'll change the token - is that slot being used elsewhere?

2020-09-22 13:12 UTC, tomt1664 commented on server/src/protocol/util.rs
> -                tx_backup_verify(&prepare_sign_msg)?;
The validity checks are done in lines 278-296. Only the locktime is critical for the security of the protocol - I don't think the server should care about output script validity or fee rates etc - this should all be handled by the wallet.

2020-09-22 21:27 UTC, tomt1664 commented on server/src/storage/monotree.rs
> +    fn get_current_backup_txs(&self, _locktime: i64) -> crate::Result<Vec<crate::structs::BackupTxID>> {
// Dummy implementation. Unused.

2020-10-16 15:19 UTC, tomossomot commented
Merge in master please, some updates are adding back outdated code.

2020-10-16 16:59 UTC, lawlawlaw commented
No longer builds

2020-10-23 10:47 UTC, lawlawlaw commented on server/src/watch.rs
> +        if #[cfg(any(test,feature="mockdb"))]{
The feature "mockdb" should refer to mocking the database only. Can you add a new feature "mockbitcoinrpc"?

2020-10-23 11:08 UTC, tomossomot commented on server/src/protocol/util.rs
> -                tx_backup_verify(&prepare_sign_msg)?;
Shouldnt we also be checking Deposit amount, fee amount and fee addresses here? Perhaps at line 304

2020-10-23 11:15 UTC, tomossomot commented on shared/src/mocks/mock_client.rs
> +pub struct MockClient {}
Name this better, there are 3 different 'Clients' throughout the codebase

2020-10-23 12:42 UTC, tomt1664 commented on server/src/protocol/util.rs
> -                tx_backup_verify(&prepare_sign_msg)?;
By fee rates, I mean the miner fee that is set in the backup transaction. As I understand it we charge the service fee only on deposit and withdrawal - the question here I guess is whether the backup tx should include an service fee paid to the SE address. I don't think it should.

2020-10-27 17:06 UTC, lawlawlaw commented
Integration tests failing:
batch_transfer_test::tests::test_batch_sigs
    batch_transfer_test::tests::test_batch_transfer
    test::tests::test_deposit
    test::tests::test_double_transfer
    test::tests::test_get_statechain
    test::tests::test_transfer
    test::tests::test_wallet_load_with_shared_key
    test::tests::test_withdraw

2020-10-30 08:44 UTC, tomossomot approved these changes

2020-11-05 17:26 UTC, merged